# Generated by Django 6.0 on 2025-12-17 12:19

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('required_for', models.CharField(choices=[('KYC', 'Know Your Customer'), ('LOAN_APPLICATION', 'Loan Application'), ('INCOME_PROOF', 'Income Verification'), ('BUSINESS_DOCS', 'Business Documentation'), ('COLLATERAL', 'Collateral Documents'), ('ADDRESS_PROOF', 'Address Verification'), ('EMPLOYMENT_PROOF', 'Employment Verification')], default='KYC', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('max_file_size', models.IntegerField(default=10485760)),
                ('allowed_extensions', models.CharField(default='pdf,jpg,jpeg,png,doc,docx', help_text='Comma-separated list of allowed file extensions', max_length=100)),
                ('verification_required', models.BooleanField(default=True, help_text='Whether this document type requires manual verification')),
                ('auto_approve', models.BooleanField(default=False, help_text='Whether documents of this type should be auto-approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('AUTO_APPROVED', 'Auto-Approved')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('download_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('verification_type', models.CharField(choices=[('MANUAL', 'Manual Verification'), ('AUTOMATED', 'Automated Verification'), ('THIRD_PARTY', 'Third Party Verification'), ('AUTO_APPROVAL', 'Auto-Approval')], default='MANUAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk assessment score (0-100)')),
                ('confidence_level', models.IntegerField(default=100, help_text='Confidence level of verification (0-100)')),
                ('ai_analysis_result', models.JSONField(blank=True, default=dict)),
                ('verification_metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='documents.document')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['document', 'timestamp'], name='documents_d_documen_bfc53a_idx'), models.Index(fields=['user', 'timestamp'], name='documents_d_user_id_a19e7c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='documents_d_user_id_200c84_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status'], name='documents_d_documen_174e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='documents_d_uploade_65506e_idx'),
        ),
    ]
