# Generated by Django 5.2.8 on 2025-12-06 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DISBURSEMENT", "Loan Disbursement"),
                            ("REPAYMENT", "Loan Repayment"),
                            ("FEE", "Processing Fee"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "mpesa_receipt",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "merchant_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "result_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("callback_received", models.BooleanField(default=False)),
                ("callback_data", models.JSONField(blank=True, null=True)),
                ("callback_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "M-Pesa Transaction",
                "verbose_name_plural": "M-Pesa Transactions",
                "db_table": "mpesa_transactions",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("DISBURSEMENT", "Loan Disbursement"),
                            ("REPAYMENT", "Loan Repayment"),
                            ("PROCESSING_FEE", "Processing Fee"),
                            ("LATE_FEE", "Late Payment Fee"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("payment_method", models.CharField(default="MPESA", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mpesa_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="payments.mpesatransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("PARTIAL", "Partial Payment"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Schedule",
                "verbose_name_plural": "Payment Schedules",
                "db_table": "payment_schedules",
                "ordering": ["due_date"],
            },
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["mpesa_receipt"], name="mpesa_trans_mpesa_r_4ee2a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["checkout_request_id"], name="mpesa_trans_checkou_3d1894_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["merchant_request_id"], name="mpesa_trans_merchan_580806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(fields=["status"], name="mpesa_trans_status_797175_idx"),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["user", "status"], name="mpesa_trans_user_id_ff2216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["reference_number"], name="payments_referen_a186d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_user_id_1b771c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_type"], name="payments_payment_ba7b87_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentschedule",
            unique_together={("payment", "due_date")},
        ),
    ]
