# Generated by Django 5.2.8 on 2025-12-09 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_make_phone_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="M-Pesa registered phone number",
                max_length=15,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")],
            ),
        ),
    ]
