# Generated by Django 5.2.8 on 2025-12-09 13:19

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("QUICK_CASH", "Quick Cash Loan"),
                            ("BUSINESS", "Business Loan"),
                            ("EMERGENCY", "Emergency Loan"),
                            ("PERSONAL", "Personal Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "loan_tenure",
                    models.PositiveIntegerField(help_text="Tenure in months"),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("loan_reference", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISBURSED", "Disbursed"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("purpose", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "credit_score_assigned",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "application_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("disbursement_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "db_table": "loans",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "min_tenure",
                    models.PositiveIntegerField(help_text="Minimum tenure in months"),
                ),
                (
                    "max_tenure",
                    models.PositiveIntegerField(help_text="Maximum tenure in months"),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "late_fee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Late fee rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "min_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_employment_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum employment duration in months"
                    ),
                ),
                ("min_credit_score", models.PositiveIntegerField(default=600)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_documents", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loan Product",
                "verbose_name_plural": "Loan Products",
                "db_table": "loan_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("PARTIAL", "Partial Payment"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Repayment Schedule",
                "verbose_name_plural": "Repayment Schedules",
                "db_table": "repayment_schedules",
                "ordering": ["due_date"],
            },
        ),
    ]
