# Generated by Django 5.2.8 on 2025-12-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayment_schedule",
                to="loans.loan",
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["user", "status"], name="loans_user_id_efac20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["loan_reference"], name="loans_loan_re_85c7e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["status", "application_date"], name="loans_status_1ac6c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repaymentschedule",
            unique_together={("loan", "installment_number")},
        ),
    ]
