# Generated by Django 5.2.8 on 2025-12-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
