# Generated by Django 5.2.8 on 2025-12-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_alter_loan_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("QUICK_CASH", "Quick Cash Loan"),
                    ("BUSINESS", "Business Loan"),
                    ("EMERGENCY", "Emergency Loan"),
                    ("PERSONAL", "Personal Loan"),
                    ("EDUCATION", "Education Loan"),
                ],
                max_length=20,
            ),
        ),
    ]
