# Generated by Django 5.2.8 on 2025-12-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_alter_loan_loan_type"),
    ]

    operations = [
        # LoanProduct model already exists in database
        # This migration does nothing to avoid duplicate table creation
    ]