# Generated by Django 5.2.8 on 2025-12-12 21:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_alter_loan_loan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "name",
                    models.CharField(max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                    ),
                ),
                (
                    "min_tenure",
                    models.PositiveIntegerField(
                        help_text="Minimum tenure in months",
                    ),
                ),
                (
                    "max_tenure",
                    models.PositiveIntegerField(
                        help_text="Maximum tenure in months",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "late_fee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Late fee rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "min_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "min_employment_duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum employment duration in months",
                    ),
                ),
                (
                    "min_credit_score",
                    models.PositiveIntegerField(default=600),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "requires_documents",
                    models.BooleanField(default=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "db_table": "loan_products",
                "verbose_name": "Loan Product",
                "verbose_name_plural": "Loan Products",
                "ordering": ["name"],
            },
        ),
    ]
