# Generated by Django 5.2.8 on 2025-12-09 13:19

import datetime
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("html_content", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                            ("IN_APP", "In-App Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("CANCELLED", "Cancelled"),
                            ("RETRYING", "Retrying"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        help_text="External provider message ID",
                        max_length=100,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                ("total_bounced", models.IntegerField(default=0)),
                ("email_sent", models.IntegerField(default=0)),
                ("email_delivered", models.IntegerField(default=0)),
                ("sms_sent", models.IntegerField(default=0)),
                ("sms_delivered", models.IntegerField(default=0)),
                ("template_performance", models.JSONField(blank=True, default=dict)),
                ("unique_recipients", models.IntegerField(default=0)),
                ("average_delivery_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=5, help_text="1=Highest, 10=Lowest"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["priority", "scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("LOAN_APPROVAL", "Loan Approval"),
                            ("LOAN_REJECTION", "Loan Rejection"),
                            ("LOAN_DISBURSEMENT", "Loan Disbursement"),
                            ("PAYMENT_CONFIRMATION", "Payment Confirmation"),
                            ("PAYMENT_REMINDER", "Payment Reminder"),
                            ("OVERDUE_NOTICE", "Overdue Notice"),
                            ("WELCOME_EMAIL", "Welcome Email"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("ACCOUNT_VERIFICATION", "Account Verification"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("SYSTEM_MAINTENANCE", "System Maintenance"),
                            ("MARKETING", "Marketing Communication"),
                            ("SUPPORT_TICKET", "Support Ticket Response"),
                            ("CUSTOM", "Custom Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="List of delivery channels"
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=200)),
                ("message_template", models.TextField()),
                ("html_template", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("retry_attempts", models.IntegerField(default=3)),
                ("retry_delay_minutes", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("HOURLY", "Hourly Digest"),
                            ("DAILY", "Daily Digest"),
                            ("WEEKLY", "Weekly Digest"),
                            ("NEVER", "Never"),
                        ],
                        default="IMMEDIATE",
                        max_length=15,
                    ),
                ),
                ("sms_notifications", models.BooleanField(default=False)),
                ("sms_phone_number", models.CharField(blank=True, max_length=15)),
                ("push_notifications", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(default=datetime.time(22, 0))),
                ("quiet_hours_end", models.TimeField(default=datetime.time(8, 0))),
                (
                    "notification_type_preferences",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
